services:
  extremerouter:
    image: rsalmn/extremerouter:latest
    container_name: extremerouter
    restart: always
    ports:
      - "20128:20128"
    volumes:
      - extremerouter-data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20128"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      HEADROOM_URL: http://headroom:8787
    depends_on:
      - headroom

  headroom:
    image: ghcr.io/chopratejas/headroom:latest
    container_name: headroom
    restart: always
    ports:
      - "8787:8787"

volumes:
  extremerouter-data:
    name: extremerouter-data
