export default {
  id: "kiro",
  priority: 10,
  alias: "kr",
  uiAlias: "kr",
  display: {
    name: "Kiro AI",
    icon: "psychology_alt",
    color: "#FF6B35",
    website: "https://kiro.dev",
    notice: {
      signupUrl: "https://kiro.dev",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  category: "free",
  transport: {
    baseUrl: "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
    baseUrls: [
      "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
      "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
      "https://q.us-east-1.amazonaws.com/generateAssistantResponse",
    ],
    format: "kiro",
    retry: {
      "429": 0,
    },
    headers: {
      "Content-Type": "application/json",
      Accept: "application/vnd.amazon.eventstream",
      "X-Amz-Target": "AmazonCodeWhispererStreamingService.GenerateAssistantResponse",
      "User-Agent": "AWS-SDK-JS/3.0.0 kiro-ide/1.0.0",
      "X-Amz-User-Agent": "aws-sdk-js/3.0.0 kiro-ide/1.0.0",
    },
    tokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authUrl: "https://prod.us-east-1.auth.desktop.kiro.dev",
    usage: {
      cwHost: "https://codewhisperer.us-east-1.amazonaws.com",
      qHost: "https://q.us-east-1.amazonaws.com",
      limitsPath: "/getUsageLimits",
    },
  },
  models: [
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", contextLength: 200000, maxOutputTokens: 128000 },
    { id: "deepseek-3.2", name: "DeepSeek 3.2", strip: ["image","audio"] },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next", strip: ["image","audio"] },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "claude-sonnet-5-thinking", name: "Claude Sonnet 5 (Thinking)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 (Thinking)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-haiku-4.5-thinking", name: "Claude Haiku 4.5 (Thinking)", contextLength: 200000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-5-agentic", name: "Claude Sonnet 5 (Agentic)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-4.5-agentic", name: "Claude Sonnet 4.5 (Agentic)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-haiku-4.5-agentic", name: "Claude Haiku 4.5 (Agentic)", contextLength: 200000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-5-thinking-agentic", name: "Claude Sonnet 5 (Thinking + Agentic)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-sonnet-4.5-thinking-agentic", name: "Claude Sonnet 4.5 (Thinking + Agentic)", contextLength: 1000000, maxOutputTokens: 128000 },
    { id: "claude-haiku-4.5-thinking-agentic", name: "Claude Haiku 4.5 (Thinking + Agentic)", contextLength: 200000, maxOutputTokens: 128000 },
    // GPT-5.6 family — 272k context window (observed July 2026)
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", contextLength: 272000, maxOutputTokens: 128000 },
    // GPT-5.6 synthetic variants
    { id: "gpt-5.6-sol-thinking", name: "GPT-5.6 Sol (Thinking)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-terra-thinking", name: "GPT-5.6 Terra (Thinking)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-luna-thinking", name: "GPT-5.6 Luna (Thinking)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-sol-agentic", name: "GPT-5.6 Sol (Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-terra-agentic", name: "GPT-5.6 Terra (Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-luna-agentic", name: "GPT-5.6 Luna (Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-sol-thinking-agentic", name: "GPT-5.6 Sol (Thinking + Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-terra-thinking-agentic", name: "GPT-5.6 Terra (Thinking + Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
    { id: "gpt-5.6-luna-thinking-agentic", name: "GPT-5.6 Luna (Thinking + Agentic)", contextLength: 272000, maxOutputTokens: 128000 },
  ],
  oauth: {
    ssoOidcEndpoint: "https://oidc.us-east-1.amazonaws.com",
    registerClientUrl: "https://oidc.us-east-1.amazonaws.com/client/register",
    deviceAuthUrl: "https://oidc.us-east-1.amazonaws.com/device_authorization",
    tokenUrl: "https://oidc.us-east-1.amazonaws.com/token",
    startUrl: "https://view.awsapps.com/start",
    clientName: "kiro-oauth-client",
    clientType: "public",
    scopes: [
      "codewhisperer:completions",
      "codewhisperer:analysis",
      "codewhisperer:conversations",
    ],
    grantTypes: [
      "urn:ietf:params:oauth:grant-type:device_code",
      "refresh_token",
    ],
    issuerUrl: "https://identitycenter.amazonaws.com/ssoins-722374e8c3c8e6c6",
    socialAuthEndpoint: "https://prod.us-east-1.auth.desktop.kiro.dev",
    socialLoginUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/login",
    socialTokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/oauth/token",
    socialRefreshUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authMethods: [
      "builder-id",
      "idc",
      "google",
      "github",
      "import",
    ],
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
